build:
  image: node:6.10-alpine
  commands:
    - make install
    - make test

publish:
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-nuget
    tag:
    - latest
    - $$COMMIT
    when:
      branch: master
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: urbit/drone-nuget
    tag:
    - $$TAG
    - $$COMMIT
    when:
      event: tag
      branch: refs/tags/*

plugin:
  name: NuGet
  desc: Publish files and artifacts to NuGet repository
  type: publish
  image: quay.io/urbit/drone-nuget
  labels:
    - nuget
