build:
  image: node:4.9
  commands:
    - make install
    - make test

publish:
  coverage:
    # Must match parts of the absolute path
    include: drone-nuget/coverage/lcov.info
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-nuget
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-nuget
    tag: develop
    when:
      branch: develop

plugin:
  name: NuGet
  desc: Publish files and artifacts to NuGet repository
  type: publish
  image: plugins/drone-nuget
  labels:
    - nuget
