kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang
    commands:
      - go build
      - go test ./...

  - name: publish
    image: plugins/docker
    settings:
      repo: plugins/drone-nuget
      auto_tag: true
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
