kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:4.2
    commands:
      - make install
      - make test
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: plugins/drone-nuget
      auto_tag: true
      when:
        branch: master
